apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
spec:
  generators:
  - git:
      repoURL: https://github.com/ptx96/fks-demo-apps.git
      revision: main
      directories:
      - path: config/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      syncPolicy:
        automated:
          prune: true 
          allowEmpty: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      project: default
      source:
        repoURL: https://github.com/ptx96/fks-demo-apps.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
